name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      # - name: Build iOS (debug)
      #   run: "xcodebuild \
      #     -workspace ios/HelloReactNative.xcworkspace \
      #     -scheme HelloReactNative \
      #     clean archive \
      #     -sdk iphoneos \
      #     -configuration Debug \
      #     -UseModernBuildSystem=NO \
      #     -archivePath $PWD/HelloReactNative \
      #     CODE_SIGNING_ALLOWED=NO"
