name: Build iOS
on:
  push:
    branches: "development-staging"
  pull_request:
    branches: "development-staging"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Decrypt secrets
        run: |
          mkdir $HOME/private
          gpg --quiet --batch --yes --decrypt --passphrase="$SERVICES_SECRET" \
          --output $HOME/private/services.tar services.tar.gpg
          tar xvf $HOME/private/services.tar
        env:
          SERVICES_SECRET: ${{ secrets.SERVICES_SECRET }}
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn test
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/Sage.xcworkspace \
          -scheme Sage \
          CODE_SIGNING_ALLOWED=NO"
